version: "3"

services:
  php-web:
    image: webdevops/php-apache:7.4-alpine
    ports:
      - "4500:4500"
    volumes:
      - ./www:/app

  mysql-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: passwd
    ports:
      - "8080:8080"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini